# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Könyvjelzők
#define bookmarks_heading Könyvjelzők

#define bookmarks_toolbarfolder Könyvjelzők eszköztár mappája
#define bookmarks_toolbarfolder_description A mappához adott könyvjelzők megjelennek a Könyvjelzők eszköztáron

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/Floorp/central/
#define getting_started Bevezetés

# LOCALIZATION NOTE (Floorp_heading):
# Floorp links folder name
#define Floorp_heading Floorp Legacy 8th

# LOCALIZATION NOTE (Floorp_help):
# link title for https://www.mozilla.org/en-US/Floorp/help/
#define Floorp_help Súgó és oktatóanyagok

# LOCALIZATION NOTE (Floorp_get_help):
# link title for https://www.mozilla.org/en-US/Floorp/help/
#define Floorp_get_help Segítség kérése

# LOCALIZATION NOTE (Floorp_customize):
# link title for https://www.mozilla.org/en-US/Floorp/customize/
#define Floorp_customize A Floorp testreszabása

# LOCALIZATION NOTE (Floorp_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define Floorp_community Segítsen!

# LOCALIZATION NOTE (Floorp_about):
# link title for https://www.mozilla.org/en-US/about/
#define Floorp_about Rólunk

# LOCALIZATION NOTE (nightly_heading):
# Floorp Nightly links folder name
#define nightly_heading Floorp Nightly erőforrások

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Floorp Nightly blog

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Mozilla hibakövető

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Mozilla fejlesztői hálózat

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/Floorp/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly tesztelői eszközök

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes Minden hibajelentése

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Mozilla

#unfilter emptyLines
