# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Kuhusu Haki Zako
rights-intro = { -brand-full-name } ni ya bure na ni programu iliyofunguliwa, imeundwa na jamii ya maelfu kutoka kote ulimwenguni. Kuna mambo machache unayofaa kujua:
rights-intro-point-1 = { -brand-short-name } imefanywa kupatikana kwako chini ya masharti ya <a data-l10n-name="mozilla-public-license-link">Leseni ya Umma ya Mozilla</a>. Hii ni kumaanisha unaweza kutumia, kunakili na kusambaza { -brand-short-name } kwa wengine.  Unakaribishwa kufanya mabadiliko kodi ya chanzo cha { -brand-short-name } kama unavyotaka ili kukidhi mahitaji yako. Leseni ya Umma ya Mozilla pia inakupa haki ya kusambaza matoleo yako yaliyobadilshwa.
rights-intro-point-2 = Hujapatiwa haki zozote za alama ya biashara au leseni kwa alama za biashara za Taasisi ya Mozilla au chama chochote, ikijumuisha uzuizi wa jina au nembo za Firefox. Maelezo ya ziada kuhusu alama za biashara yanaweza kupatikana <a data-l10n-name="mozilla-trademarks-link">hapa</a>.
rights-intro-point-3 = Vipengele vingine katika { -brand-short-name }, kama vile Kiripoti Kukwama, hukupa chaguo la kutoa maoni kwa { -vendor-short-name }. Kwa kuchagua kufikisha maoni, unapatia { -vendor-short-name } ruhusa ya kutumia maoni kuboresha bidhaa, kuchapisha maoni katika tovuti, na kusambaza maoni hayo.
rights-intro-point-4 = Una uhakika gani wa kutumia maelezo na maoni yaliyofikishwa kwa { -vendor-short-name } kupitia { -brand-short-name } inaelezewa katika <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Sera ya Faragha</a>.
rights-intro-point-4-unbranded = Sera zozote za faragha zinazotumika kwa bidhaa hii zinafaa kuorodheshwa hapa.
rights-intro-point-5 = Baadhi ya Vipengee vya { -brand-short-name } hutumia huduma za maelezo zilizojikita kwenye tovuti, hata hivyo, hatuwezi kudhamini kuwa ni 100% sahihi au hazina makosa. Maelezo zaidi, ikijumulisha maelezo kuhusu jinsi ya kulemaza vipengee vinavyotumia huduma hizi, yanaweza patikana kwenye <a data-l10n-name="mozilla-service-terms-link">masharti ya huduma</a>.
rights-intro-point-5-unbranded = Kama bidhaa hii inajumulisha huduma za tovuti, masharti yoyote yanayoweza kutumika kwa huduma hii yanafaa kuungwa kwa <a data-l10n-name="mozilla-website-services-link">Huduma za Wavuti</a> sehemu.
rights-webservices-header = { -brand-full-name } Huduma za Maelezo yaliyojikita kwenye Wavuti
rights-safebrowsing = <strong>Kuvinjari salama: </strong>Kulemaza vipengee vya Kuvinjari Salama hakupendekezwi kwani kunaweza kusababisha kwenda kwenye tovuti ambazo sio salama.   Kama ungependa kulemaza kipengee kikamilifu, fuata hatua hizi:
rights-safebrowsing-term-1 = Fungua mapendeleo ya programu
rights-safebrowsing-term-2 = Fungua chaguo za Usalama
rights-safebrowsing-term-4 = Kuvinjari Salama sasa kumelemazwa
rights-locationawarebrowsing = <strong>Kuvinjari Mahali Kujua: </strong>kila wakati iko kwenye chaguo.   Hakuna maelezo ya mahali yamewahi kutumwa bila idhini.   Kama ungependa kulemaza kipengee kikamilifu, fuata hatua hizi:
rights-locationawarebrowsing-term-1 = Katika pau wa URL, aina <code>kuhusu:usanidi</code>
rights-locationawarebrowsing-term-2 = Aina geo.imewezeshwa
rights-locationawarebrowsing-term-3 = Bofya mara mbili kwenye upendeleo wa geo.enabled
rights-locationawarebrowsing-term-4 = Mahali-Kuvinjari Kujua sasa kumelemazwa
rights-webservices-unbranded = Mapitio ya huduma za wavuti ambazo bidhaa inajumuisha, pamoja na maagizo ya jinsi ya kuyalemaza, kama yanaweza kutumika, yanafaa kujumuishwa hapa.
rights-webservices-term-unbranded = Masharti yoyote ya huduma yanaweza kutumika kwa bidhaa hii yanafaa kuorodheshwa hapa.
rights-webservices-term-1 = { -vendor-short-name } na wachangiaji wake, waleseni na wenzi hufanya kazi kutoa Huduma sahihi zaidi na za kisasa. Hata hivyo, hatuwezi kudhamini kuwa maelezo haya ni ya kuaminika na hayana makosa.    Kwa mfano, Huduma ya Kuvinjari Salama haiwezi kutambua tovuti zingine na inaweza kutambua tovuti zingine kimakosa na Huduma ya Mahali Kujua mahali pote kumerudishwa na watoaji huduma ni kisio tu na watoaji huduma hudhamini usahihi wa mahali walipotoa.
rights-webservices-term-2 = { -vendor-short-name } yaweza kukatiza au kubadilisha Huduma kwa hiari yake.
rights-webservices-term-3 = Unakaribishwa kutumia Huduma hizi na matoleo yanayoandamana ya { -brand-short-name } na { -vendor-short-name } inakupa haki ya kufanya hivyo.   { -vendor-short-name } na waleseni wake huhifadhi haki zingine zote katika Huduma.   Masharti haya hayakusudiwi kuzuia haki zozote zilizotolewa chini ya leseni zilizofunguliwa kutumiwa na { -brand-short-name } na kuandikiana na matoleo ya chanzo cha { -brand-short-name }.
rights-webservices-term-4 = <strong>Huduma zinatolewa "kama-ni".   { -vendor-short-name }, wachangiaji wake, waleseni, na wagawanyaji, wanakataa kumiliki udhamini, ulio wa moja kwa moja au uliokusudiwa, ikijumulisha bila kuzuia, udhamini ambao Huduma zinaweza kuuzwa na kukidhi matumizi fulani.   Unachukua hararii kubwa ya kuchagua Huduma kwa matumizi yako na kwa ubora na ufanya kazi wa Huduma hizo. Ugawaji mwingine hauruhusu utenganisho au uzuizi wa udhamini, kwa hivyo kutodai kwako hakukuhusu.</strong>
rights-webservices-term-5 = <strong>Isipokuwa inavyohitajika na sheria, { -vendor-short-name }, wachangiaji wake, waleseni na wagawanyaji hawatawajibika kwa madhara ya moja kwa moja, maalum, ya matukio, yenye madhara, au madhara yasiyo ya kawaida yanayotokana kwa njia yoyote yakihusiana na utumizi wa { -brand-short-name } na Huduma hiyo.   Uwajibikaji wa pamoja chini ya masharti haya hautakiuka $500 (dol mia tano). Mamlaka mengine hayaruhusu utenagaji au uzuiaji wa madhara, kwa hivyo utengaji na uzuiaji haukuhusu.</strong>
rights-webservices-term-6 = { -vendor-short-name } yaweza kusasaisha masharti haya kama inavyohitajika kupitia wakati. Masharti haya hayabadilishwi au kukatizwa bila makubaliano yaliyoandikwa ya { -vendor-short-name }.
rights-webservices-term-7 = Masharti haya yanatawaliwa na sheria za taifa la Califonia, U.S.A., ikitenga mgogoro wa utoaji wa sheria. Kama kipande chochote cha masharti haya kitachukuliwa kuwa batili au hakiwezi kutekelezwa, sehemu zilizobaki zitakuwa na nguvu na athari. Wakati ambapo kuna mgogoro kati ya toleo lililotafsiriwa la masharti na toleo la Kiingereza, toleo la Kiingereza litakuwa na udhibiti.
