# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Par jiusu tīseibom
rights-intro = { -brand-full-name } ir breiva bezmoksys attaiseituo koda programa, kū veidoj tyukstušym breivpruoteigū nu vysys pasaules. Ir dažys lītys, kū jiusim byutu vārts zynot:
rights-intro-point-1 = { -brand-short-name } ir pīejams ar <a data-l10n-name="mozilla-public-license-link">Mozilla publiskuos licences</a>nūsaciejumym. Tys nūzeimei, ka jius varot breivi izmantuot, pavairuot iz izplateit { -brand-short-name } cytim.  Taipat jius drūsais varot maineit i papyldynuot { -brand-short-name } pyrmskodu piec sovim īskotym. Mozilla publiskā licence dūd jiusim tīseibys breivi izplateit sovys modificeituos versejis.
rights-intro-point-2 = Mozilla nadūd jiusim tīseibys izmantuot Mozilla i Firefox preču zeimes i logo. Papyldus informaceja par preču zeimom ir atrūnoma <a data-l10n-name="mozilla-trademarks-link">ite</a>.
rights-intro-point-3 = Dažys nu { -brand-short-name } īspiejom, pīmāram, avareju gadiejumu zinuošona reiks, pīduovoj jiusim īspieju nūsyuteit sovu vīdūkli par { -vendor-short-name }. Izavālūt nūsyuteit sovu vīdūkli, jius dūdit atļaunu { -vendor-short-name } izmantuot itū jiusu snīgtū informaceju, kab uzlobuotu sovus produktus, publiceit to sovuos sātys lopuos voi kai cytaidi izplateit itū sajimtū informaceju.
rights-intro-point-4 = Tys kai mes izmontojam jiusu personiskū informaceju i { -vendor-short-name } nūsyuteitū vīdūkli izmontojūt { -brand-short-name } ir apraksteits <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } privatuma politikā</a>.
rights-intro-point-4-unbranded = Vysom aktualajom privatuma politikom byutu juobyut uzskateitom ite.
rights-intro-point-5 = Dažys { -brand-short-name } īspiejis izmontoj šķārsteiklā bāzeitus pakolpuojumus, taču, mes navarom garanteit, ka tī ir 100% pareizi i klaidu breivi. Papyldus informaceja par itim pakolpuojumym i to kai tūs deaktivēt, ir pīejama <a data-l10n-name="mozilla-service-terms-link">pakolpuojumu nūsaciejumu aprokstā</a>.
rights-intro-point-5-unbranded = Nui itymā produktā ir īkļauti šķārsteikla pakolpuojumi, vysim aktualajim pakolpuojuma nūsaciejumym juobyut pīejamym <a data-l10n-name="mozilla-website-services-link">sātys lopu pakolpuojumu</a> škirklī.
rights-intro-point-6 = In order to play back certain types of video content, { -brand-short-name } downloads certain content decryption modules from third parties.
rights-webservices-header = { -brand-full-name } šķārsteiklā bāzeitī informacejis pakolpuojumi
rights-webservices = { -brand-full-name } izmontoj šķārsteiklā bāzeitus informacejis pakolpuojumus ("Pakolpuojumi"), kab nūdrūsynuotu dažys nu funkcejom, kas pīejamys binarajā { -brand-short-name } versejī ar zamuok apraksteitajim nūsaciejumym. Nui nasavielejit izmantuot kaidu nu apraksteitajim pakolpuojumym voi ari to izmontuošonys nūsaciejumi jiusim nav pījemami, jius varot deaktiveit itūs pakolpuojumus. Instrukcejis, kai deaktivēt konkretu pakolpuojumi ir pīejamys <a data-l10n-name="mozilla-disable-service-link">ite</a>. Cytys īspiejis i pakolpuojumus var deaktivēt programys īstatiejumūs.
rights-safebrowsing = <strong>Drūsā puorlūkuošona: </strong>Drūsūs puorlūkuošonys deakticiešona nav īteicama, kam itaidā veidā jius varot nūnuokt nadrūsuos šķārsteikla lopuos. Nui tūmār vālotīs to deaktivēt, reikojitīs sekūjūši:
rights-safebrowsing-term-1 = Attaisit programys īstatiejumus
rights-safebrowsing-term-2 = Izavielit šķirkļu Drūseiba
rights-safebrowsing-term-3 = Uncheck the option to "{ enableSafeBrowsing-label }"
enableSafeBrowsing-label = Block dangerous and deceptive content
rights-safebrowsing-term-4 = Drūsā puorlūkuošona tagad ir deaktiveita
rights-locationawarebrowsing = <strong>Atsarasšona vītu zynuša puorlūkuošona: </strong>informaceja par jiusu atsarasšona vītu nikod natīk syuteita bez jiusu pīkrišonys.  Nui vālotīs pilneibā deaktivēt itū īspieju, reikojitīs sekūjūši:
rights-locationawarebrowsing-term-1 = Adresi juslā īrkostit <code>about:config</code>
rights-locationawarebrowsing-term-2 = Īrkostit geo.enabled
rights-locationawarebrowsing-term-3 = Ar dubultklikški uzklikškinojit iz geo.enabled īstatiejuma
rights-locationawarebrowsing-term-4 = Vītu zynūšuo puorlūkuošona tagad ir deaktiveita
rights-webservices-unbranded = Pīejamū sātys lopu pakolpuojumu aproksti i instrukcejis kai vajadzeibys gadiejumā deaktivēt tūs ir pīejami ite.
rights-webservices-term-unbranded = Aktualajim pakolpuojumu izmontuošonys nūsacejumym byutu juobyut apraksteitim ite.
rights-webservices-term-1 = { -vendor-short-name } kūpā ar breivpruoteigajim, licenču partnerim i partnerim struodoj pi tei, kab nūdrūsynuotu vysprecizuokūs i aktualuokūs pakolpuojumus. Taču mes navarom garanteit, ka itei informaceja ir vysaptverūša i bez klaidom. Pīmāram, drūsūs puorlūkuošonys pakolpuojums var nazynot, ka kaida lopa ir beistama voi ari klaidainai uzskateit kaidu drūsu lopu par beistamu. Myusu partneru pīduovuotuo atsarasšona vītys nūsaceišona ir tikai aptuvana i nadz mes, nadz myusu partneri nagarantej pīduovuotuos atsarasšona vītys informacejis pareizeibu.
rights-webservices-term-2 = { -vendor-short-name } var puortraukt Pakolpuojumus piec sovim īskotym.
rights-webservices-term-3 = Mes laipnai lyudzam jius izmantuot itūs { -brand-short-name } pīduovuotūs pakolpuojumus, i { -vendor-short-name } snīdz jiusim tīseibys to dareit.  { -vendor-short-name } i tuos licenču partneri patur vysys cytys tīseibys itymūs pakolpuojumūs.  Itī nūsaciejumi nav dūmuoti, kab īrūbežuotu jiusu tīseibys, kū jiusim snīdz ar { -brand-short-name } saisteituos attaiseituo koda licences voi { -brand-short-name } pyrmskoda licences.
rights-webservices-term-4 = <strong>Pakolpuojumi tīk pīduovuoti "kaidi tī ir."  { -vendor-short-name }, tuos paleig, licencētuoji i izplateituoji atsasoka nu sevkaidā garantejom, naatkareigi nu tei voi tuos ir paustys rakstiski voi tīk pījemtys kai asūšys, īskaitūt sevkaidys garantejis par to, ka Pakolpuojumi ir funkcionali i atbiļstūši jiusu vajadzeibom.  Vysa atbiļdeiba par Pakolpuojumu izmontuošonu gulstys iz jiusu placym attīceibā iz to kvalitati i atbiļsteibu veicamajom funkcejom.  Zynomūs juridiskuos apstuokļūs nav īspiejams atsasaceit nu īdūmuotajom garantejom, leidz ar to itei atruna var iz jiusim naatsateikt.</strong>
rights-webservices-term-5 = <strong>Izjemūt gadiejumus, kur to pīprosa lykumdūšona, { -vendor-short-name }, tuos paleigi, licencētuoji i izplateituoji nabyus atbiļdeigi par sevkaidim teišym, natīšim, najaušim voi sevkaidim cyta veida būjuojumym, kas sevkaidā veidā saistomi ar { -brand-short-name } i tei Pakolpuojumu izmontuošonu.  Kūpejuo atbiļdeiba piec itū nūsaciejumu principym napuorsnīgs $500 (pīcus symtus ASV dolaru). Zynomūs juridiskuos apstuokļūs nav īspiejams atsasaceit nu īdūmuotajom garantejom, leidz ar to itei atruna var iz jiusim naatsateikt.</strong>
rights-webservices-term-6 = { -vendor-short-name } dreikst breivi maineit voi papyldynuot itūs nūsaciejumus piec sovim īskotym. Itī nūsaciejumi navar tikt modificeiti voi atcalti bez īprīkšejā rakstiska aplīcynuojuma nu { -vendor-short-name }.
rights-webservices-term-7 = These terms are governed by the laws of the state of California, U.S.A., excluding its conflict of law provisions. If any portion of these terms is held to be invalid or unenforceable, the remaining portions will remain in full force and effect. In the event of a conflict between a translated version of these terms and the English language version, the English language version shall control.
