# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = I tiei dirits
rights-intro = { -brand-full-name } al è un program a gratis e open source, realizât di une comunitât di miârs di contributôrs che a son a stâ par dut il mont. Ve ca alc che tu varessis di savê:
rights-intro-point-1 = { -brand-short-name } al è disponibil sot i tiermins dal <a data-l10n-name="mozilla-public-license-link">Mozilla Public License (Licence Publiche di Mozilla) </a>. Chest al vûl dî che tu puedis doprâ, copiâ e distribuî { -brand-short-name } a altris.  Tu puedis ancje modificâ il codiç sorzint di { -brand-short-name } come che tu vuelis seont lis tôs disbisugnis.  Cun di plui la Mozilla Public License ti da il dirit di distribuî lis tôs versions modificadis.
rights-intro-point-4-unbranded = Cualsisei politiche di privacy relatîf a chest prodot al varès di jessi listât ca.
rights-webservices-term-unbranded = Cualsisei tiermin di servizi aplicabil par chest prodot al varès di jessi elencât culì.
rights-webservices-term-2 = { -vendor-short-name } al pues fermâ o cambiâ i Servizis a sô discrezion.
rights-webservices-term-4 = <strong>I Servizis a son furnîts "as-is."  { -vendor-short-name }, chei che a àn contribuît, i licenziataris e i distributôrs a dinein dutis lis garanziis, sei esplicitis sei implicitis, includint cence limitazion lis garanziis che i Servizis a son vendibii e adats pai tiei specifics fins. Tu âs dut il riscjo te selezion dai Servizis pai tiei fins e pe cualitât e pes prestazions dai Servizis. Cualchi jurisdizion no permet la esclusion o la limitazion des garanziis implicitis, par cui chest messaç podarès no jessi aplicabil par te.</strong>
rights-webservices-term-5 = <strong>Fûr che pai recuisîts di leç, { -vendor-short-name }, chei che a àn contribuît, i licenziataris e i distributôrs no saran persegubii par cualsisei dam indiret, speciâl, incidentâl, conseguenziâl, punitîf o esemplâr che al ves di vignî fûr di o leât in cualsisei mût al ûs di { -brand-short-name } e dai Servizis. La perseguibilitât coletive sot di chescj tiermins no sarà plui di $500 (cinc cent dolars). Cualchi jurisdizion no permet la esclusion o la limitazion des garanziis implicitis, par cui chest messaç podarès no jessi aplicabil par te.</strong>
rights-webservices-term-6 = { -vendor-short-name } al pues inzornâ chescj tiermins secont la necessitât di tant in tant. Chescj tiermins no puedin jessi modificâts o cancelâts cence un acuart scrit di { -vendor-short-name }.
rights-webservices-term-7 = Chescj tiermins a son governâts des leçs dal stât de Californie, U.S.A., escludint i conflits cu lis cundizions de leç. Se cualsisei part di chescj tiermins e je valutade no valide o no aplicabile, lis parts che a restin a restaran in plen valôr e efiet. Intal câs che al vegni fûr un conflit tra la version voltade di chescj tiermins e la version par inglês, la version par inglês e varà valôr legâl.
