# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title 書籤
#define bookmarks_heading 書籤

#define bookmarks_toolbarfolder 個人書籤列
#define bookmarks_toolbarfolder_description 此處的書籤會出現於書籤工具列上

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/Floorp/central/
#define getting_started 新手上路

# LOCALIZATION NOTE (Floorp_heading):
# Floorp links folder name
#define Floorp_heading Floorp Legacy 8th

# LOCALIZATION NOTE (Floorp_help):
# link title for https://www.mozilla.org/en-US/Floorp/help/
#define Floorp_help 說明和教學

# LOCALIZATION NOTE (Floorp_get_help):
# link title for https://www.mozilla.org/en-US/Floorp/help/
#define Floorp_get_help 取得幫助

# LOCALIZATION NOTE (Floorp_customize):
# link title for https://www.mozilla.org/en-US/Floorp/customize/
#define Floorp_customize 自訂 Floorp

# LOCALIZATION NOTE (Floorp_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define Floorp_community 參與我們

# LOCALIZATION NOTE (Floorp_about):
# link title for https://www.mozilla.org/en-US/about/
#define Floorp_about 關於我們

# LOCALIZATION NOTE (nightly_heading):
# Floorp Nightly links folder name
#define nightly_heading Floorp Nightly 資源

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Floorp Nightly 部落格

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Mozilla Bug Tracker

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Mozilla Developer Network

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/Floorp/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly 測試者工具

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes 您遇到過的所有錯誤

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Planet Mozilla

#unfilter emptyLines
