#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Segnalibri
#define bookmarks_heading Segnalibri

#define bookmarks_toolbarfolder Cartella della barra dei segnalibri
#define bookmarks_toolbarfolder_description Aggiungere un segnalibro a questa cartella per mostrarlo nella barra dei segnalibri

# LOCALIZATION NOTE (getting_started):
# link title for http://www.mozilla.com/en-US/Floorp/central/
#define getting_started Come iniziare

# LOCALIZATION NOTE (Floorp_heading):
# Floorp links folder name
#define Floorp_heading Floorp Legacy 8th

# LOCALIZATION NOTE (Floorp_get_help):
# link title for http://www.mozilla.com/Floorp/help/
#define Floorp_get_help Ottieni assistenza

# LOCALIZATION NOTE (Floorp_customize):
# link title for http://www.mozilla.com/en-US/Floorp/customize/
#define Floorp_customize Personalizza Floorp

# LOCALIZATION NOTE (Floorp_community):
# link title for http://www.mozilla.com/en-US/Floorp/community/
#define Floorp_community Collabora con noi

# LOCALIZATION NOTE (Floorp_about):
# link title for http://www.mozilla.com/en-US/Floorp/about/
#define Floorp_about Informazioni

# LOCALIZATION NOTE (nightly_heading):
# Floorp Nightly links folder name
#define nightly_heading Risorse per Floorp Nightly

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Floorp Nightly blog

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Mozilla - Segnalazione bug

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Mozilla Developer Network

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/Floorp/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly Tester Tools

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes Elenco degli arresti anomali

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Pianeta Mozilla

#unfilter emptyLines
