# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Mayelana namalungelo wakho
rights-intro = I-{ -brand-full-name } i-software ekhululekile enomthombo ovulekile, eyakhiwe izinkulungewane zomphakathi emhlabeni jikelele. Kunezinto ezombalwa okufanelele uzazi:
rights-intro-point-1 = I-{ -brand-short-name } yenziwe ukuba itholakale kuwe ngaphansi kwemigomo ye- <a data-l10n-name="mozilla-public-license-link">Ilayisense esobala ye-Mozilla</a>. Lokhu kusho ukuthi ungasebenzisa, ukopishe futhi usabalalise i-{ -brand-short-name } kwabanye.  Futhi wamukelekile ukuba ushintshe ikhodi yomthombo ye-{ -brand-short-name } njengoba ufuna ukuhlangabezana nezidingo zakho. Ilayisense ye-Mozilla esobala futhi ikunika ilungelo lokusabalalisa izinguqulo zakho ozishintshile.
rights-intro-point-2 = Awunikiwe ilungelo lophawu lokuthengisa noma ilayisense lokuthengiswa kwe-Mozilla Foundation noma okunye, kufaka phakathi ngaphandle komkhawulo wegama noma uphawu lwe-Firefox. Ulwazi olungeziwe kumaphawu wokuthengisa lungatholakala <a data-l10n-name="mozilla-trademarks-link">lapha</a>.
rights-intro-point-3 = Ezinye izici ku-{ -brand-short-name }, njengesibiki sokusaphazeka, sikunika ukukhetha ukunikela ngempendulo ku-{ -vendor-short-name }. Ngokukhetha ukuhambisa impendulo, unika i-{ -vendor-short-name } imvume yokusebenzisa ipendulo ukuthuthukisa imikhiqizo yayo, ukushicilela impendulo kumawebhusayithi wayo, futhi nokusabalalisa impendulo.
rights-intro-point-4 = Ukuthi siyisebenzisa kanjani imininingwne yakho efihlekile nompendulo ehanjiswe ku-{ -vendor-short-name } nge-{ -brand-short-name } kuchazwa ku- <a data-l10n-name="mozilla-privacy-policy-link">Inqubomgomo yemfihlo ye-{ -brand-short-name }</a>.
rights-intro-point-4-unbranded = Noma iyiphi inqubomgomo yemfihlo yalo mkhiqizo kufanele fakwe ohlwini lapha.
rights-intro-point-5 = Ezinye izici ze-{ -brand-short-name } zisebenzisa izinsizakalo zolwazi ezigxile kwiwebhu, noma kunjalo, ngeke sikwazi ukuqinisekisa ukuba azinamaphutha angu-100%. Imininingwane eminingi, kufaka phakathi ulwazi lokuba ungazikhubaza kanjani izici ezisebenzisa lezo zinsizakalo, lungatholakala ku <a data-l10n-name="mozilla-service-terms-link">imigomo yensizakalo</a>.
rights-intro-point-5-unbranded = Uma lo mkhiqizo ungenisa izinsizakalo zewebhu, noma imiphi imigomo yensizakalo wezinsizakalo kufanele zihlanganiswe ku <a data-l10n-name="mozilla-website-services-link">Izinsizakalo zewebhusayithi</a> isigaba.
rights-webservices-header = Izinsizakalo zolwazi ezigxile kwiwebhu ye-{ -brand-full-name }
rights-webservices = I-{ -brand-full-name } isebenzisa izinsizakalo zolwazi ezigxile kwiwebhu ("Izinsizakalo") ukuze inikele ngezinye zezici ongazisebenzisa nale nguqulo eyenziwe ngeziqu ezimbili ye-{ -brand-short-name } ngaphansi kwemigomo echazwe ngezansi. Uma ungafuni ukusebenzisa insizakalo eyodwa noma ezingaphezulu noma imigomo engezansi ayamukelekile, ungakhubaza isici noma izinsizakalo. Imiyalo yokuthi ungasikhubaza kanjani isici noma insizakalo ethile ingatholakalo <a data-l10n-name="mozilla-disable-service-link">lapha</a>. Ezinye izici nezinsizakalo zingakhutshazwa kuzintandokazi zohlelo lokusebenza.
rights-safebrowsing = <strong>i-SafeBrowsing: </strong>Ukukhubaza isici sokudlulisa amehlo ngokuvikelekile asinconyiwe njengoba kungakuholela kumasayithi angavikelekile.  Uma ufuna ukukhubaza isici sonke, landela lezo zinyathelo:
rights-safebrowsing-term-1 = Vula izintandokazi zohlelokusebenza
rights-safebrowsing-term-2 = Khetha ukukhethwa kokuvikeleka
rights-safebrowsing-term-4 = Ukudlulisa amehlo manje kukhutshaziwe
rights-locationawarebrowsing = <strong>Ukudlulisa amehlo okuqondene nendawo: </strong>kuhlala kufakiwe.  Alukho ulwazi lwendawo okuthunyelwayo ngaphandle kwemvume yakho.  Uma uthanda ukukhubaza isici sonke, landela lezi zinyathelo:
rights-locationawarebrowsing-term-1 = Emugqei we-URL, bhala <code>mayelana:isimiso</code>
rights-locationawarebrowsing-term-2 = Bhala geo.ukunikwa amandla
rights-locationawarebrowsing-term-3 = Chofoza kabili ezintandokazini zokunikeni amandla ze-geo
rights-locationawarebrowsing-term-4 = Ukudlulisa amehlo kokuqonda kwendawo manje kukhutshaziwe
rights-webservices-unbranded = Ukufinqwa kwezinsizakalo zewebhusayithi umkhiqizo uhlanganisa, nemiyalo ekubeni ungazikhubaza kanjani, uma kukhona, kufanele kufakwe lapha.
rights-webservices-term-unbranded = Noma iyiphi inqubomgomo yensizakalo yalo mkhiqizo kufanele fakwe ohlwini lapha.
rights-webservices-term-1 = I-{ -vendor-short-name } nababambe iqhaza kuyo, izikhungo esinikezela ngelayisense nozakwethu basebenza ukunikela ngensizakalo elungile futhi esesikhathini samanje.  Noma kunjalo, ngeke sikwazi ukuqinisekisa ukuba lolu lwazi luyazwisiseka futhi alunamaphutha.  Isibonelo, insizakalo yokudlulisa amehlo ngokuvikelekile ngeke ikwazi ukubona amanye amasayithi ayingozi futhi ingabona amanye amasayithi avuikelekile ngephutha futhi nensizakalo yendawo yokuqonda zonke izindawo ezibuyiswa ngabanikeli bezinsizakalo bethu ziyacabangelwa kuphela futhi yithi, hhayi abanikeli ngezinsizakalo bethu, abaqinisekisa ukulunga kwezindawo ezikiwe.
rights-webservices-term-2 = I-{ -vendor-short-name } ingahle ingasaqhubeki noma ishintshe izinsizakalo ngozikhethela kwayo.
rights-webservices-term-3 = Wamukelekile ukusebenzisa lezi zinsizakalo ngenguqulo ehambsana nayo ye-{ -brand-short-name }, ne-{ -vendor-short-name } zikunika amalungelo wazo wokwenza njalo.  I-{ -vendor-short-name } nezikhungo ezinikezela ngelayisense igodle wonke amalungelo ezinsizakalweni.  Leyo migomo akuhloswanga ngawo ukukhawulela amalungelo anikiwe ngaphansi kwamalayisense womthombo ovulekile afunekayo ku-{ -brand-short-name } nakuzinguqulo zekhodi yomthombo ehambelanoyo ye-{ -brand-short-name }.
rights-webservices-term-4 = <strong>Izinsizakalo zinikelwa "nje-nge."  { -vendor-short-name }, abanikeli, izikhungo ezinikezela ngelayisense nabasabalalisi bayo bakhipha zonke iziqinisekiso, zigcizelela noma ziqondisiwe, kufaka phakathi ngaphandle komkhawulo, iziqinisekiso ukuba izinsizakalo ziyathengiswa futhi zifanele izinhloso sakho ezithile.  Uvemelana nayo yonke ingozi ngokukhetha izinsizakalo zezinhloso zakho futhi njengakukhwalithi nokusebenza kwezinsizakalo. Ezinye izindawo ethile azivumeli ukukhishwa noma ukukhawulelwa kweziqiniseko ezicatshangelwe, ngakho-ke lo mshwana wokuzikhipha emthwalweni kungenzeka ungasebenzi kuwe.</strong>
rights-webservices-term-5 = <strong>Ngaphandle kokuba kudingeke ngokomthetho, i-{ -vendor-short-name }, abanikeli, izikhungo ezinikezela ngelayisense, nabasabalalisi bayo ngeke baphoqeleka ngokomthetho kokunye nokunye okungaqondene, okukhethekile, okwenzeka kungahleliwe, okungagudluki, okujezisayo noma amacala wokungagudluki angenayo naphumayo nganoma iyiphi indlela ehlobene nokusetshenziswa kwe-{ -brand-short-name } nezonsizakalo.  Iqoqo lesibopho sezomthetho ngaphansi kwaleyo migomo ngeke lidlule ku-$500 (amadola angamakhulu amahlanu). Ezinye izindawo ethile azivumeli ukukhishwa noma ukukhawulelwa kweziqiniseko ezicatshangelwe, ngakho-ke lo mshwana wokuzikhipha emthwalweni kungenzeka ungasebenzi kuwe.</strong>
rights-webservices-term-6 = I-{ -vendor-short-name } ngavuselela leyo migomo ngokudingekile njalo nje. Leyo migomo ngeke ishintshwe noma ikhanselwe ngaphandle kwesivumelwano esibhaliwe se-{ -vendor-short-name }.
rights-webservices-term-7 = Leyo migomo ibuswa yimithetho yezwe lase-California, e-U.S.A., ngaphandle kokuphambana kokunikelwa komthetho wayo. Uma enye inxenye kule migomo ayivumelekile noma eyingafezekiseki, izinxenye ezisele zizohlala zisebenza ngokufanele nangokungenamkhawulo. Esigabeni sokuphikisana phakathi kwenguqulo ehumushiwe yaleyo migomo nengukulo yesiNgisi, inguqulo yesiNgisi izolawula.
