# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title Закладки
#define bookmarks_heading Закладки

#define bookmarks_toolbarfolder Папка панели закладок
#define bookmarks_toolbarfolder_description Добавьте закладки в эту папку, чтобы увидеть их на панели закладок

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/Floorp/central/
#define getting_started Начальная страница

# LOCALIZATION NOTE (Floorp_heading):
# Floorp links folder name
#define Floorp_heading Floorp Legacy 8th

# LOCALIZATION NOTE (Floorp_help):
# link title for https://www.mozilla.org/en-US/Floorp/help/
#define Floorp_help Справка и руководства

# LOCALIZATION NOTE (Floorp_get_help):
# link title for https://www.mozilla.org/en-US/Floorp/help/
#define Floorp_get_help Получить помощь

# LOCALIZATION NOTE (Floorp_customize):
# link title for https://www.mozilla.org/en-US/Floorp/customize/
#define Floorp_customize Настройте под себя Floorp

# LOCALIZATION NOTE (Floorp_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define Floorp_community Присоединяйтесь к сообществу

# LOCALIZATION NOTE (Floorp_about):
# link title for https://www.mozilla.org/en-US/about/
#define Floorp_about О нас

# LOCALIZATION NOTE (nightly_heading):
# Floorp Nightly links folder name
#define nightly_heading Ресурсы Floorp Nightly

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog Блог Floorp Nightly

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla Трекер ошибок Mozilla

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn Сеть разработчиков Mozilla

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/Floorp/addon/nightly-tester-tools/
#define nightly_tester_tools Nightly Tester Tools

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes Все ваши падения

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet Планета Mozilla

#unfilter emptyLines
