# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title ഓര്‍മ്മക്കുറിപ്പുകള്‍


#define bookmarks_heading ഓര്‍മ്മക്കുറിപ്പുകള്‍


#define bookmarks_toolbarfolder ഓര്‍മ്മക്കുറിപ്പുകള്‍ക്കുള്ള ടൂള്‍ബാര്‍ ഫോള്‍ഡര്‍


#define bookmarks_toolbarfolder_description ഓര്‍മ്മക്കറിപ്പുകളുടെ ടൂള്‍ബാറില്‍ പ്രദര്‍ശിപ്പിയ്ക്കുന്നതിനായി ഈ ഫോള്‍ഡര്‍ ഓര്‍മ്മക്കുറിപ്പുകളായി ചേര്‍ക്കുക


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started ഉപയോഗിച്ചു് തുടങ്ങുക


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading മോസില്ലാ ഫയര്‍ഫോക്സ്


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help സഹായങ്ങള്‍


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize ഫയല്‍ഫോക്സ് യഥേഷ്ടമാക്കുക


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community പങ്ക് ചേരൂ


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about ഞങ്ങളെപ്പറ്റി


# LOCALIZATION NOTE (nightly_heading):


# Firefox Nightly links folder name


#define nightly_heading Firefox Nightly Resources


# LOCALIZATION NOTE (nightly_blog):


# Nightly builds only, link title for https://blog.nightly.mozilla.org/


#define nightly_blog Firefox Nightly blog


# LOCALIZATION NOTE (bugzilla):


# Nightly builds only, link title for https://bugzilla.mozilla.org/


#define bugzilla Mozilla Bug Tracker


# LOCALIZATION NOTE (mdn):


# Nightly builds only, link title for https://developer.mozilla.org/


#define mdn Mozilla Developer Network


# LOCALIZATION NOTE (nightly_tester_tools):


# Nightly builds only, link title for https://addons.mozilla.org/en-US/firefox/addon/nightly-tester-tools/


#define nightly_tester_tools Nightly Tester Tools


# LOCALIZATION NOTE (crashes):


# Nightly builds only, link title for about:crashes


#define crashes All your crashes


# LOCALIZATION NOTE (irc):


# Nightly builds only, link title for ircs://irc.mozilla.org/nightly


#define irc Discuss Nightly on IRC


# LOCALIZATION NOTE (planet):


# Nightly builds only, link title for https://planet.mozilla.org/


#define planet Planet Mozilla


#unfilter emptyLines
