# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-intro = { -brand-full-name }je wòlną i ôpenzdrojową softwôrą ùsôdzoną przez wieletësãczną spòlëznã z całégò swiata. Nót je tuwò pamiãtac ò czile sprawach:
rights-intro-point-1 = { -brand-short-name }je przistãpny za zgòdã zastrzedżi<a data-l10n-name="mozilla-public-license-link">Mozilla Pùblicznô Licencëja</a>. Òznaczô to że mòżesz ùżëwac, kòpérowac i wespółdzelëc { -brand-short-name } z jinyma. Mòżesz téż zjinaczac zdrojowi kòd { -brand-short-name } bë dopasowac gò dlô twòji pòtrzébnotë. Pùblicznô Licencjô Mozillë daje téż mòżnotã distribùcje nej zmòdifikòwóny wersji.
rights-intro-point-2 = Ni môsz praw patentowich do znaków Fùndacje Mozilla i zrzeszonëch z nią firmów, w tim w całoscë do miona i loga Firefox. Wicy wëdowiédzë ò zastrzeżonëch znakach jidze nalezc na <a data-l10n-name="mozilla-trademarks-link">tuwò</a>.
rights-intro-point-3 = Niechtërné fùnkcje { -brand-short-name }, taczi jak Crash Reporter dôwają mòżlëwòtã sélania òpinii do { -vendor-short-name }. Jeżlë zdecydëjesz sã na wësłônié òpinii, dajesz { -vendor-short-name } zezwòlenié ji ùżëcé dlô pòprawë jich wërobiznów, ópùblikòwônié dbë na stronie internetowi, i ji distribucje.
rights-intro-point-4 = Jak më ùżëwômë wëdowiédzã ò ce i òpiniach wësłónëch do { -vendor-short-name } przez { -brand-short-name } je òpisóné w <a data-l10n-name="mozilla-privacy-policy-link">{ -brand-short-name } Pòlitika priwatnoscë</a>.
rights-intro-point-4-unbranded = Wszëtczé pasowné wskôzë priwatnotë dlô ny softwôrë nót je tuwò pòdac.
rights-intro-point-5 = Niechtërné { -brand-short-name } òptacje programù ùżëwają sécowëch ùsłëżnotów i ni mòżemë zazychrowac że wszëtczé wëdowiédzë są 100% akùratné i bezzmiłkòwé. Wicy detali i wëdowiédzë ò tim jak wëłączëc ne òptacje jidze nalezc w <a data-l10n-name="mozilla-service-terms-link">Leżnoscë brëkòwaniô serwisu</a>.
rights-intro-point-5-unbranded = Żlë nen program brëkùje sécowi ùsłëżnotë, wszëtczé przënôléżné zastrzédżi nót je czierowac do <a data-l10n-name="mozilla-website-services-link">Ùsłëżnotë stronë</a>sekcjô.
rights-webservices-header = { -brand-full-name } sécowé ùsłëżnotë wëdowiédzë
rights-webservices = { -brand-full-name } spùscô sã na sécowé ùsłëżnotë wëdowiédzë ("Services") żebë przëdac, pòd zastrzégóma, niechtërnëch z òptacje dostãpnëch przë ùżiwôniô wjistalownóny wersji { -brand-short-name }. Jeżlë nie chcesz ùżëwac jedny czë wicy z nych ùsłëżnotów, abò nie zgôdzôsz sã z zastrzégóma, mòżesz ne ùsłëżnotë wëłączëc. instrukcje ò tim jak je wëłączëc jidze nalezc <a data-l10n-name="mozilla-disable-service-link">tuwò</a>. Jiné fùnkcje i ùsłëdżi mòże włączëc w òstatwach aplikacje.
rights-safebrowsing = <strong>Bezpieczé przezéranié: </strong>Wëłączanié bezpiecznégò przezérania nie je zamòdlëwôné jakno że daje to przistãp do niebezpiecznëch stronów. Jeżlë jednak chcesz wëłączëc nã òptacjã, trzim sã pòniższëch kroków:
rights-safebrowsing-term-1 = Òtemkni preferencje aplikacje
rights-safebrowsing-term-2 = Wëbierzë ùstawë bezpiekù
rights-safebrowsing-term-4 = Bezpieczné przezéranié je wëłączoné
rights-locationawarebrowsing = <strong>Pòłóżenié-wiédné przezéranié: </strong>je wiedno sugerowónô. Wëdowiédzô ò pòłóżenim nigdë nie je séloné bez pòzwòleniô. Jeżlë jednak chcesz czësto wëłączëc ną òptacjã, trzim sã pòniższëch kroków:
rights-locationawarebrowsing-term-1 = W lëstwie adresu URL, wpiszë <code>about:config</code>
rights-locationawarebrowsing-term-2 = ôrt geo.włączony
rights-locationawarebrowsing-term-3 = Dwaklëkni na geo.włączoné nastawë
rights-locationawarebrowsing-term-4 = Pòłóżenié-wiedné przezéranié je terô włączonô
rights-webservices-unbranded = Zesëmòwanié brëkòwónëch sécowëch ùsłëżnotów i instrukcjô tegò jak mòże je wëłączëc Jeżlë bãdze takô pòtrzéba, nót je pòdac tuwò.
rights-webservices-term-unbranded = Wszëtczé zastrzedżi ùsłëżnotów, chtërne nen produkt ùżëwô, mają bëc tuwò pòdóné.
rights-webservices-term-1 = { -vendor-short-name }jegò ùsôdcë, licencjôdôwôczé, i partnerzë mają starã ò to żebë zazychrowac nôbarżi akùratné i aktùalné ùsłëżnotë. Jednak ni mómë gwësnotë że wëdowiédzë są bezzmiłkòwé. Na przëmiôr, bezpieczné przezeranié mòże nie rozpòznac niechtërnëch niebezpiecznëch stron abò zgłaszac bezpieczné stronã jakno niebezpieczé. Pòłóżenié-wiédné przezéranié zanôlégô òd tëch co nã ùsłëżnotã dają i sã le òbszacowanim. Më ani dôwôcze ùsłëżnotów nie dajemë zôrãki że ne wëdowiédzë są akùratné.
rights-webservices-term-2 = { -vendor-short-name } mòże przeriwac abò zmieniac ùsłëżnotë wedle ùznaniô.
rights-webservices-term-3 = Mòżesz swòbòdno ùżëwac nëch ùsłëżnotów i dołożony wersji { -brand-short-name }, { -vendor-short-name } daje ce do tegò prawa. { -vendor-short-name } i jegò licencjodôwôcze zastrzégają  sobie wszétczé prawa. Ne zastrzedżi ni mają na ùdbie ògrańczania prawów przënôléżnëch pòd zastrzegóma Ôpen Ùdbów tikôjących sã { -brand-short-name } i sparłãczony zdrojowi kòd { -brand-short-name }.
rights-webservices-term-4 = <strong>Ne ùsłëżnotë sã dôwôné "tak jak są." { -vendor-short-name }, jich ùsôdcë, licencjodôwôczé, i rozprowôdzërzé, òdżegnywôją sã òd dôwôni gwarancje, nawetka jeżlë bëłë òne wësłowaczóné czë sugòrowóné, łączno z ògrańczenioma, gwarancjama że ne ùsłëżnotë sã na przedôż i zabezpieczą przëdzelony zgrôw. Rizykò sparłąconé z wëbiérkã nëch ùsłëżnotów, jich kwalitetu czë spòlëglëwòtë dlô swòjich célów spòcziwô na Ce. Kò wedle niechtërnëch prawów, ni mòże nie ùważac zakłôdónëch gwarancje, tak że nen bôczënk mòże sã Ce nie tëkac.</strong>
rights-webservices-term-5 = <strong>Z wëjimkôma dze nakazëje to prawò, { -vendor-short-name },jich ùsôdcë, licencjôdôwôczé, i rozprowôdzërzé, nie sã òdpòwiedzalni za niżóden bezpòstrzédny, òsoblëwi, pòstrzédny, przëtrôfkòwy, niepòpùstny,  karny, czë wënôdgrodë wënikającé ze szkòdów pòwstałëch przë ùżiwónim { -brand-short-name } i ùsłëżnotë. Całownota òdpòwiedzalnoscë pòd nym prawã ni mòże przekroczëc 5 tësącë dolarów amerikańsczich ($500). Wedle niechtërnch prawów, ni mòże nie ùwôżac zakłôdónëch gwarancje, tak że nen bôczënk mòże sã Ce nie tëkac.</strong>
rights-webservices-term-6 = { -vendor-short-name } mòże òd czasu do czasu zmienic ne zastrzédżi, Żlë bãdze nót. Ne zastrzédżi ni mògą bëc zjinaczoné czë òdwołóné bez { -vendor-short-name }pisowny zgòdë.
rights-webservices-term-7 = Ne zastrzédżi są òpiarté na prawach merëkańsczégò stónu Kalifarnia, prócz wëjimków dze jistnieją kònfliktë z jinyma prawama. Nawetka żlë dzéle zastrzégów są niewôżné, reszta zastrzégów mùszi bëc respektowónô. W przëtrôwkù dze pòwstôł kònflikt midzë zdolmôczoną a angielską wersją zastrzégów, angielskô wersjô biérze górã.
