# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = Ka ga ditokelo tša gago
rights-intro = { -brand-full-name } ke lenaneo-tirišo la khomphutha la bolokologi le la mothopo o bulegilego, leo le agilwego ke setšhaba sa batho ba dikete bao ba tšwago lefaseng ka bophara. Go na le dilo tše mmalwa tšeo o swanetšego go di tseba:
rights-intro-point-1 = { -brand-short-name } e dirilwe gore e hwetšagale go wena ka tlase ga maemo a <a data-l10n-name="mozilla-public-license-link">Laesense ya Setšhaba ya Mozilla</a>. Se se bolela gore o ka diriša, kopiša le go phatlalatša { -brand-short-name } go batho ba bangwe.  Gape o amogelegile gore o ka fetoša khoutu ya mothopo ya { -brand-short-name } ka ge o nyaka go fihlelela dinyakwa tša gago. Laesense ya Setšhaba ya Mozilla gape e go nea tokelo ya go phatlalatša dikgatišo tšeo o di fetošitšego.
rights-intro-point-2 = Ga se wa newa ditokelo dife goba dife tša leswago goba dilaesense tša maswao a Mozilla Foundation goba leloko lefe goba lefe, go akaretšwa eupša go sa lekanyetšwa go leina goba leswao la Firefox. Tshedimošo e oketšegilego ka maswao e ka hwetšwa<a data-l10n-name="mozilla-trademarks-link">mo</a>.
rights-intro-point-3 = Dibopego tše dingwe go { -brand-short-name }, tše bjalo ka sebegi sa go pšhatlega, di go nea kgetho ya go fana ka dipoelo go { -vendor-short-name }. Ka go kgetha go romela dipoelo, o nea { -vendor-short-name } tumelelo ya go diriša dipoelo gore e kaonafatše ditšweletšwa tša yona, go phatlalatša dipoelo diwepesaeteng tša yona, le go aba dipoelo gape.
rights-intro-point-4 = Kamoo re dirišago tshedimošo ya gago le dipoelo tšeo di rometšwego go { -vendor-short-name } ka { -brand-short-name } di hlalositšwe go <a data-l10n-name="mozilla-privacy-policy-link">pholisi ya bosephiri ya { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Dipholisi dife goba dife tša sephiri tšeo di šomago tša setšweletšwa se di swanetše go lokeletšwa mo.
rights-intro-point-5 = Dibopego tše dingwe tša { -brand-short-name } di diriša ditirelo tša tshedimošo yeo e theilwego wepeng, le ge go le bjalo re ka se tiišetše gore di nepagetše 100% goba ga di na phošo le gatee. Dintlha tše dingwe, go akaretša le tshedimošo ya kamoo o ka šitišago dibopego tšeo di dirišago ditirelo tše, e ka hwetšwa go <a data-l10n-name="mozilla-service-terms-link">maemong a tirelo</a>.
rights-intro-point-5-unbranded = Ge eba setṧweletšwa se se akaretša ditirelo tša wepe, maemo afe goba afe a tirelo ao a šomago a (di)tirelo a swanetše go lomaganywa le tiro ya <a data-l10n-name="mozilla-website-services-link">Ditirelo tša wepesaete</a> wepesaete.
rights-webservices-header = Ditirelo tša tshedimošo tše theilwego wepeng tša { -brand-full-name }
rights-webservices = { -brand-full-name } e diriša ditirelo tša tshedimošo tše theilwego wepeng ("Services") gore e fane ka tše dingwe tša dibopego tšeo di newago gore o di diriše le tokollo ya tše pedi ya { -brand-short-name } ka tlase ga melawana e hlalositšwego ka mo tlase. Ge e ba o sa nyake go diriša e nngwe ya ditirelo goba melawana yeo e lego ka mo tlase e sa amogelege, o ka šitiša sebopego goba (di)tirelo. Ditaelo mabapi le kamoo o ka šitišago sebopego se itšego goba tirelo di ka hwetšwa  <a data-l10n-name="mozilla-disable-service-link">mo</a>. Dibopego tše dingwe le ditirelo di ka šitišwa go dikganyogwa tša tirišo.
rights-safebrowsing = <strong>Go praosa go bolokegilego:</strong>Go šitiša sebopego sa go praosa mo go bolokegilego ga go eletšwe ka ge go ka feleletša ka gore o ye disaeteng tše sa bolokegago. Ge e ba o nyaka go šitiša sebopego ka mo go feletšego, latela megato ye:
rights-safebrowsing-term-1 = Bula dikganyogo tša tirišo
rights-safebrowsing-term-2 = Kgetha kgetho ya tšhireletšego
rights-safebrowsing-term-4 = Go praosa mo go bolokegilego bjale go šitišitšwe
rights-locationawarebrowsing = <strong>Go praosa ga go lemoga lefelo:</strong>ka mehla e a kgethwa. Ga go na tshedimošo ya lefelo yeo e romelwago ka ntle le tumelelo ya gago. Ge e ba o nyaka go šitiša sebopego ka mo go feletšego, latela megato ye:
rights-locationawarebrowsing-term-1 = Go para ya URL, ngwala <code>mabapi le:peakanyo</code>
rights-locationawarebrowsing-term-2 = Ngwala geo.enabled
rights-locationawarebrowsing-term-3 = Kgotla gabedi go kganyogo ya geo.enabled
rights-locationawarebrowsing-term-4 = Go praosa ga go lemoga lefelo bjale go šitišitšwe
rights-webservices-unbranded = Kakaretšo ya ditirelo tša wepesaete tšeo setšweletšwa se di akaretšago, gotee le ditaelo tša kamoo di ka šitišwago ka gona, ge e ba di šoma, di swanetše go akaretšwa mo.
rights-webservices-term-unbranded = Maemo afe goba afe a tirelo ao a šomago a setšweletšwa se a swanetše go lokeletšwa mo.
rights-webservices-term-1 = { -vendor-short-name } le batsenya-letsogo ba yona, ba dilaesense le badirišani ba yona ba šoma go fana ka ditirelo tše nepagetšego le tšeo di lego nakong. Le ge go le bjalo, re ka se tiišetše gore tshedimošo ye e phethagetše e bile ga e na phošo le gatee. Ka mohlala, tirelo ya go praosa mo go bolokegilego e ka no se lemoge tše dingwe tša disaete tšeo di lego kotsi gape e ka lemoga tše dingwe tša disaete tšeo di bolokegilego ka phošo gape tirelo ya go lemoga lefelo, mafelo ka moka ao a tlišwago ke baabi ba rena ba tirelo ke diphopholetšo feela gomme rena goba baabi ba rena ba ditirelo ga re tiišetše go nepagala ga mafelo ao a filwego.
rights-webservices-term-2 = { -vendor-short-name } e ka kgaotša goba ya fetoša ditirelo go ya kamoo yona e bonago e le gabohlale.
rights-webservices-term-3 = O amogelegile go diriša ditirelo tše le kgatišo yeo e sepelago le tšona ya { -brand-short-name }, gomme { -vendor-short-name } e go nea ditokelo tša yona tša gore o ka dira bjalo.  { -vendor-short-name } le banei ba yona ba laesense ba boloka ditokelo tše dingwe ka moka ditirelong.  Melao ye ga se ya ikemišetša go lekanyetša ditokelo dife goba dife tšeo di filwego ka tlase ga dilaesense tša mothopo wo o bulegilego tšeo di šomago go { -brand-short-name } le go dikgatišo tša khoutu ya motheo yeo e sepelelanago le { -brand-short-name }.
rights-webservices-term-4 = <strong>Ditirelo di newa go ya "kamoo di lego ka gona." { -vendor-short-name }, batsenya-letsogo ba yona, badilaesense, le baphatlalatši ba ganetša dikaranti ka moka, go sa šetšwe gore di boletšwe goba di šišintšwe, go akaretšwa ka ntle le tekanyetšo, dikaranti tšeo ditirelo di rekwago le tšona e bile di swanela morero wa gago o itšego.  O rwala maikarabelo a kotsi ka moka a go kgetha ditirelo bakeng sa merero ya gago gotee le boleng le tsela ya go šoma ga ditirelo. Dikahlolo tše dingwe ga di dumelele go se akaretšwe goba tekanyetšo ya dikaranti tšeo di šišintšwego, ka gona kganetšo ye e ka no se šome go wena.</strong>
rights-webservices-term-5 = <strong>Ka ntle le ge go nyakwa ke molao, { -vendor-short-name }, batsenya-letsogo ba yona, badilaesense, le baphatlalatši ba ka se ikarabele ka tshenyo ya go lebanya, e kgethegilego, e kopanego le maemo, ditlamorago, kotlo, goba tša mohlala tšeo di tšwelelago go goba ka go tswalana ka tsela efe goba efe le tirišo ya { -brand-short-name } le ditirelo.  Maikarabelo ao a kgobokeditšwego ka tlase ga melao ye a ka se fete $500 (ditolara tše makgolo a mahlano). Dikahlolo tše dingwe ga di dumelele go se akaretšwe goba tekanyetšo ya ditshenyo tše itšego, ka gona go se akaretšwe mo le tekanyetšo di ka no se šome go wena.</strong>
rights-webservices-term-6 = { -vendor-short-name } e ka mpshafatša melao ye go ya ka mo go nyakegago nako le nako. Melao ye e ka no se fetošwe goba go khanselwa ka ntle le tumelelo yeo e ngwadilwego fase ya { -vendor-short-name }.
rights-webservices-term-7 = Melao ye e bušwa ke melao ya naga ya California, U.S.A., go sa akaretšwe go lwantšhana ga yona le molao wa kabo. Ge eba karolo efe goba efe ya melao ye e sa šome goba e ka se gapeletšwe, dikarolo tšeo di šetšego di tla šala di šoma ka mo go feletšego. Tabeng yeo go yona go bago le go thulana magareng ga kgatišo yeo e fetoletšwego le kgatišo ya leleme la Seisemane, go tla laola kgatišo ya leleme la Seisemane.
