# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

rights-title = N-wï kúe
rights-intro = { -brand-full-name } kue nak software libre, re men thus kuey na li chen pees . Nakin lo beel kue:
rights-intro-point-2 = No se le concede ningún derecho ni licencia sobre las marcas comerciales de Mozilla Foundation o sus filiales, incluyendo sin limitación el nombre y logo de Firefox. Puede encontrarse información adicional sobre las marcas comerciales <a data-l10n-name="mozilla-trademarks-link">Trée</a>.
rights-intro-point-3 = Algunas características en { -brand-short-name }, como el agente de informe de fallos, le dan la opción de proporcionar información a { -vendor-short-name }. Al elegir enviar esa información, concede a { -vendor-short-name } permiso para usar la misma para mejorar sus productos, para publicar esa información en sus sitios web y para distribuirla.
rights-intro-point-4 = La manera en que usamos su información personal y las opiniones enviadas a { -vendor-short-name } a través de { -brand-short-name } se describe en<a data-l10n-name="mozilla-privacy-policy-link">Política de privacidad de { -brand-short-name }</a>.
rights-intro-point-4-unbranded = Cualquier política de privacidad aplicable a este producto se debe listar aquí.
rights-webservices-unbranded = Aquí debe incluirse un resumen de los servicios de sitios web que el producto incorpora, junto con instrucciones de cómo deshabilitarlas, si se aplica.
rights-webservices-term-unbranded = Cualquier término de servicio para este producto debe ser listado aquí.
rights-webservices-term-1 = { -vendor-short-name } y sus colaboradores, licenciatarios y socios trabajan para proporcionar los servicios más precisos y actualizados. Sin embargo, no podemos garantizar que esta información sea completa y esté libre de errores. Por ejemplo, el servicio de navegación segura puede no identificar algunos sitios peligrosos y puede identificar algunos sitios seguros por error y las direcciones devueltas por nuestros proveedores del servicio de navegación basada en la ubicación son sólo estimaciones y ni nosotros ni nuestros proveedores garantizamos la exactitud de las ubicaciones proporcionadas.
rights-webservices-term-2 = { -vendor-short-name } puede discontinuar o cambiar los servicios a su albedrío.
rights-webservices-term-3 = Puede usar estos servicios con la versión correspondiente de { -brand-short-name }, y { -vendor-short-name } le otorga derechos para hacerlo. { -vendor-short-name } y sus licenciatarios se reservan el resto de derechos de los servicios. Estos términos no limitan ningún derecho otorgado por las licencias de código abierto aplicables a { -brand-short-name } y las versiones del código fuente correspondiente de { -brand-short-name }.
rights-webservices-term-4 = <strong>Los servicios son provistos "tal cual".  { -vendor-short-name }, sus colaboradores, licenciatarios y distribuidores, rechazan toda garantía, así donde esté expresado o donde esté implícito, incluyendo y sin limitarse, garantías de que el servicio es comerciable y que cumple con su necesidad particular. Usted conlleva el riesgo seleccionado de este servicio para su propósito así como a la calidad y desempeño del servicio. Algunas jurisdicciones no permiten la exclusión o limitación de las garantías implícitas, así que esta denegación puede no aplicarse en su caso.</strong>
rights-webservices-term-5 = <strong>Excepto donde sea requerido por la ley, { -vendor-short-name }, sus colaboradores, licenciatarios y distribuidores no podrán ser responsables de ningún daño indirecto, especial, imprevisto, resultante, punitivo o ejemplar relacionado con el uso de { -brand-short-name } y los servicios. La responsabilidad colectiva bajo estos términos no podrán exceder los US$500 (quinientos dólares). Algunas jurisdicciones no permiten la exclusión o limitación de ciertos daños, así que esta exclusión y limitación puede no ser aplicable para usted.</strong>
rights-webservices-term-6 = { -vendor-short-name } puede actualizar estos términos si es necesario de tiempo en tiempo. Estos términos no pueden ser modificados o cancelados sin el consentimiento por escrito de { -vendor-short-name }.
rights-webservices-term-7 = Estos términos están regidos por las leyes del estado de California, EE.UU., excluyendo sus conflictos con otras estipulaciones de la ley. Si cualquier parte de estos términos es posible que sea inválida o inexigible, las porciones restantes continuarán teniendo su efecto total. En el caso de haber un conflicto entre una versión traducida de estos términos y la versión en idioma Inglés, la versión en Inglés será la que tendrá el control.
