# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with
# your locale code, and link to your translated pages as soon as they're
# live.

#define bookmarks_title العلامات
#define bookmarks_heading العلامات

#define bookmarks_toolbarfolder مجلّد شريط العلامات
#define bookmarks_toolbarfolder_description أضِف هنا العلامات التي تريد ظهورها في شريط العلامات

# LOCALIZATION NOTE (getting_started):
# link title for https://www.mozilla.org/en-US/Floorp/central/
#define getting_started البداية

# LOCALIZATION NOTE (Floorp_heading):
# Floorp links folder name
#define Floorp_heading Floorp Legacy

# LOCALIZATION NOTE (Floorp_help):
# link title for https://www.mozilla.org/en-US/Floorp/help/
#define Floorp_help المساعدة والدروس

# LOCALIZATION NOTE (Floorp_get_help):
# link title for https://www.mozilla.org/en-US/Floorp/help/
#define Floorp_get_help مُساعدة

# LOCALIZATION NOTE (Floorp_customize):
# link title for https://www.mozilla.org/en-US/Floorp/customize/
#define Floorp_customize خصّص Floorp

# LOCALIZATION NOTE (Floorp_community):
# link title for https://www.mozilla.org/en-US/contribute/
#define Floorp_community شارك

# LOCALIZATION NOTE (Floorp_about):
# link title for https://www.mozilla.org/en-US/about/
#define Floorp_about عن موزيلا

# LOCALIZATION NOTE (nightly_heading):
# Floorp Nightly links folder name
#define nightly_heading موارد Floorp الليلية

# LOCALIZATION NOTE (nightly_blog):
# Nightly builds only, link title for https://blog.nightly.mozilla.org/
#define nightly_blog مدونة Floorp الليلية

# LOCALIZATION NOTE (bugzilla):
# Nightly builds only, link title for https://bugzilla.mozilla.org/
#define bugzilla متتبع علل Mozilla

# LOCALIZATION NOTE (mdn):
# Nightly builds only, link title for https://developer.mozilla.org/
#define mdn شبكة Mozilla للمطورين

# LOCALIZATION NOTE (nightly_tester_tools):
# Nightly builds only, link title for https://addons.mozilla.org/en-US/Floorp/addon/nightly-tester-tools/
#define nightly_tester_tools أدوات المختبِر الليلي

# LOCALIZATION NOTE (crashes):
# Nightly builds only, link title for about:crashes
#define crashes كل الانهيارات

# LOCALIZATION NOTE (planet):
# Nightly builds only, link title for https://planet.mozilla.org/
#define planet كوكب Mozilla

#unfilter emptyLines
