# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#filter emptyLines

# LOCALIZATION NOTE: The 'en-US' strings in the URLs will be replaced with

# your locale code, and link to your translated pages as soon as they're

# live.


#define bookmarks_title Takku


#define bookmarks_heading Takku


#define bookmarks_toolbarfolder Banqaasu bopp


#define bookmarks_toolbarfolder_description Yokk ay takku ci wayndare bi boo leen bëggee gis ci banqaasu bopp


# LOCALIZATION NOTE (getting_started):


# link title for https://www.mozilla.org/en-US/firefox/central/


#define getting_started Ci yoonu tambali


# LOCALIZATION NOTE (firefox_heading):


# Firefox links folder name


#define firefox_heading Mosiyaa faayafoks


# LOCALIZATION NOTE (firefox_help):


# link title for https://www.mozilla.org/en-US/firefox/help/


#define firefox_help Ndimbal ak gindeekukaay


# LOCALIZATION NOTE (firefox_customize):


# link title for https://www.mozilla.org/en-US/firefox/customize/


#define firefox_customize Solal Faayafoks


# LOCALIZATION NOTE (firefox_community):


# link title for https://www.mozilla.org/en-US/contribute/


#define firefox_community Jàpp leen ci !


# LOCALIZATION NOTE (firefox_about):


# link title for https://www.mozilla.org/en-US/about/


#define firefox_about Ci mbirum Mozilla


#unfilter emptyLines
